language: objective-c
osx_image: xcode9.1

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install xcpretty -N
  - gem install cocoapods
  - gem install cocoapods-acknowledgements
  - pod install

script:
  - xcodebuild clean -workspace ChemKeyboard.xcworkspace -scheme ChemKeyboard -destination 'platform=iOS Simulator,name=iPhone 8' -sdk iphonesimulator build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO | xcpretty -c
