fastlane_version "2.63.0"

default_platform :ios

platform :ios do
  lane :beta do
    gym(
      workspace: "ChemKeyboard.xcworkspace",
      scheme: "ChemKeyboard",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "tech.chemopin.ChemKeyboard" => "ChemKeyboard iOS Development Provisioning Profile",
          "tech.chemopin.ChemKeyboard.Keyboard" => "ChemKeyboard Keyboard iOS Development Provisioning"
        }
      }
    )

    crashlytics(
      api_token: "a310c7f3be9676421bbbcf654222bb76f8ece4d5",
      build_secret: "5dcd2ea38efce77c7c503afe8e5c5806f677acb7f468bb5532c7cfe6e7525e5f"
    )
  end
end
